export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const SHOW_CART = "SHOW_CART"
export const HIDE_CART = "HIDE_CART"
export const READ_SCREENWIDTH = "READ_SCREENWIDTH"

export const UPDATE_CART = "UPDATE_CART"
export const GET_TOTAL_CART = "GET_TOTAL_CART"
export const REMOVE_ITEM = "REMOVE_ITEM"
